name: Check typos

on:
  push:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  typos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: typos-action
        uses: crate-ci/typos@v1.22.3
